# Generated by Django 4.2.11 on 2025-08-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view books'), ('can_create', 'Can create book'), ('can_edit', 'Can edit books'), ('can_delete', 'Can delete book')]},
        ),
    ]
