# Generated by Django 4.2.11 on 2025-08-23 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 12, 31, 16, 829629)),
        ),
    ]
