# Generated by Django 5.2.5 on 2025-08-23 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 13, 13, 38, 553659, tzinfo=datetime.timezone.utc)),
        ),
    ]
